In [1]:
import pandas as pd
import numpy as np

## 상가정보_서울 동대문구만 추출

In [17]:
df = pd.read_csv("C:/Users/user/Desktop/소상공인시장진흥공단_상가(상권)정보_서울_202206.csv", encoding='utf-8')
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23324279,제중건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1156010600100410002034626,NaN,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,NaN,1,NaN,126.907168,37.520613
1,24525909,민속악기사,NaN,D,소매,D04,취미/오락관련소매,D04A09,악기판매,G47593,...,1120012200101420011000227,NaN,서울특별시 성동구 용답5길 2,133849,4803.0,NaN,NaN,NaN,127.049018,37.566857
2,24715368,태평양진주,NaN,D,소매,D26,시계/귀금속소매,D26A01,시계/귀금속,G47830,...,1111015200100440000000001,금사랑투빌딩,서울특별시 종로구 서순라길 17-10,110390,3138.0,NaN,NaN,NaN,126.993530,37.571848
3,15554136,김선희꼼꼼국어교습소,NaN,R,학문/교육,R01,학원-보습교습입시,R01A01,학원-입시,P85501,...,1171011100101970003017195,NaN,서울특별시 송파구 위례성대로12길 31,138834,5640.0,NaN,2,NaN,127.121520,37.510967
4,17174175,비지트,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010100108540018009586,상랑의빌딩,서울특별시 서초구 동광로18길 82,137837,6572.0,NaN,1,NaN,126.991394,37.488375

In [22]:
df = df.drop(df[df['시군구명'] != "동대문구"].index)

In [24]:
df.to_csv("./소상공인시장진흥공단_상가(상권)정보_동대문구_202206.csv", encoding='euckr')

## 공동주택_단지_면적정보 전용면적 나누기

In [28]:
df2 = pd.read_csv("C:/tobeO_V220414/tobeO_V220414/Data_02.ShadeCanopy/단지면적/20220801_단지_면적정보_동대문구.csv", encoding='euckr')

In [30]:
df2.head()

,시도,시군구,읍면,동리,단지코드,단지명,동수,연면적,관리비부과면적,주거전용면적,전용면적,세대수,건축물대장연면적
0,서울특별시,동대문구,NaN,답십리동,A10023891,청계푸르지오시티,1,"11,266.29","11,266.29","6,546.66",18.92,219,"7,130.64"
1,서울특별시,동대문구,NaN,답십리동,A10023891,청계푸르지오시티,1,"11,266.29","11,266.29","6,546.66",30.42,79,"4,135.65"
2,서울특별시,동대문구,NaN,답십리동,A10025754,답십리파크자이,9,"98,512.28","65,787.09","47,844.21",33.05,60,"2,907.00"
3,서울특별시,동대문구,NaN,답십리동,A10025754,답십리파크자이,9,"98,512.28","65,787.09","47,844.21",45.38,60,"3,923.40"
4,서울특별시,동대문구,NaN,답십리동,A10025754,답십리파크자이,9,"98,512.28","65,787.09","47,844.21",49.27,62,"4,395.99"

In [96]:
df2[(df2['전용면적'] <= 40) & (df2['단지명'] == '청계푸르지오시티')]

,시도,시군구,읍면,동리,단지코드,단지명,동수,연면적,관리비부과면적,주거전용면적,전용면적,세대수,건축물대장연면적
0,서울특별시,동대문구,NaN,답십리동,A10023891,청계푸르지오시티,1,"11,266.29","11,266.29","6,546.66",18.92,219,"7,130.64"
1,서울특별시,동대문구,NaN,답십리동,A10023891,청계푸르지오시티,1,"11,266.29","11,266.29","6,546.66",30.42,79,"4,135.65"